Develop test3 pull request
lardc/hw-ECMultiplexerBoard pull request #3
Opened 2020-07-01 11:18 UTC by asytyi-work

2020-07-01 11:23 UTC, asytyi submitted a review, later dismissed
Что-то проверил, что-то написал

2020-07-01 11:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		ii++;
Просто комментарий

2020-07-01 11:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +		}
```suggestion
		{
			SPI_WriteByte(SPI1, 000);
		}

```
Здесь заменить

2020-07-01 11:23 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +void CONTROL_FullSetRelay()
Это переделать

2020-07-01 11:23 UTC, asytyi commented on Firmware/Source/Controller/DebugActions.h
> +void DEBAGACTIONS_GenerateImpulseLineSync2();
```suggestion
void DEBAGACTIONS_GenerateImpulseLineSync228();

```

2020-07-01 11:26 UTC, asytyi-work commented on Firmware/Source/Controller/Controller.c
> +		ii++;
Просто ответ

2020-07-01 11:26 UTC, asytyi-work commented on Firmware/Source/Controller/Controller.c
> +		ii++;
Здесь резолв

2020-07-01 11:26 UTC, asytyi-work commented on Firmware/Source/Controller/Controller.c
> +		}
Здесь просто ответ без резолва

2020-07-01 11:34 UTC, asytyi requested changes
Just asking questions

2020-07-01 11:34 UTC, asytyi commented on Bootloader/Source/BoardConfig.h
> +#define __BOARD_CONFIG_H
wtf?

2020-07-01 11:34 UTC, asytyi commented on Bootloader/Source/BoardConfig.h
> +#include "ZwTIM.h"
wtf2?

2020-07-01 11:35 UTC, asytyi-work commented on Bootloader/Source/BoardConfig.h
> +#include "ZwTIM.h"
fixed2

2020-07-01 11:36 UTC, asytyi-work commented on Bootloader/Source/BoardConfig.h
> +#define __BOARD_CONFIG_H
fixed

2020-07-01 11:37 UTC, asytyi approved these changes

2020-07-02 20:05 UTC, VShurdov commented
Поправил

2020-07-02 20:17 UTC, VShurdov commented
Не корректно отображается в GH табы, т.к. в TrueStd, в строке стоит разное кол-во табов, а GH воспринимает их как пробел. Пикча с TrueStd
![image](https://user-images.githubusercontent.com/67577492/86405495-23df5800-bcba-11ea-8b44-21a6e3f32e85.png)

2020-07-03 12:55 UTC, asytyi commented
Комментарии к коммитам пляшут кто в лес, кто по дрова. Надо всегда помнить цель комментария — **получение быстрой информации при беглом просмотре списка коммитов**.
Конкретные замечания по комментариям к коммитам:
1. В начале комментария использовать глагол в пассивном залоге: "добавлено, исправлено, удалена и т.д."
2. Если занимаешься массовым рефакторингом названий функций во всей библиотеке — сделай это одним коммитом. 
 Простыня с коммитами отдельных функций только засоряет историю коммитов. Название для этого коммита сделать, например, "Приведены в соответствие со стандартом имена функций в библиотеке InitConfig.c". Всё. Аналогично с другими правками.

2020-07-03 13:24 UTC, asytyi requested changes

2020-07-03 13:24 UTC, asytyi commented on Firmware/Source/Controller/InitConfig.h
> +void INITCFG_�onfigTimer7();
Спасибо гитхабу, что искажает русские символы.

2020-07-03 13:24 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +volatile Int8U RelayByte[11];
11 негритят? котят? апельсинов?

2020-07-03 13:24 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +//------------------------------------------
Что функция конфигурации реле делает в файле Controller? Какая магия должна произойти при (i == 3) || (i == 4) || (i == 5) || (i == 6) ?
Если я захочу включить какое-то реле в функции мне надо открывать схему определять какой бит и в какой регистр писать, рассчитывать битовую маску и только потом вызывать функцию?

Это надо переделать по-человечески:
1.  Должна быть таблица коммутации, к полям которой можно обращаться по именованным define
(Пример здесь d:\proton\Test equipment\Commutation Unit\High Voltage\CU HV\Controller Soft\Version 2.0\CUControlBoard\Sources\Controller\CommutationTable.c)
2. Естественно отдельной библиотекой
3. Продумать работу с бистабильными, чтобы на верхнем уровне это не превращалось в пляску с масками.

Например, одновременно хочу включить бистабильные реле SW_POW1, SW_POW2 и выключить SW_POW3. Чтобы в коде это было как-то так:

```
// Формируем маску
COMM_SwitchBiStable(SW_POW1, true)
COMM_SwitchBiStable(SW_POW2, true)
COMM_SwitchBiStable(SW_POW3, false)
// Включаем реле. На выбранные реле подалось и снялось напряжение
COMM_SwitchBiStableApply()
```

2020-07-14 14:05 UTC, asytyi requested changes
Набросал как должны выглядеть функции. Осталось удалить  старый код и всё причесать. CommutationTable.h уйдёт полностью.

2020-07-14 14:05 UTC, asytyi commented on Firmware/Source/Controller/Commutation.h
> +COMM_BistableSwitch COMM_SwitchBUSLVPlusToPOW1 = {{REGISTER_A, BIT1}, {REGISTER_A, BIT2}, {REGISTER_A, BIT3}, {REGISTER_A, BIT4}};
@VShurdov предлагаю немного пересмотреть подход и оперировать при коммутации сущностями-структурами по аналогии с инициализацией GPIO.

1. Для обычного реле структура RegisterPin будет содержать номер регистра и номер бита, здесь ничего необычного.
2. Для бистабильных реле структура будет содержать четыре пары RegisterPin. У нас бистабильные реле соединены ветками по две штуки, и нет необходимости ими управлять отдельно. Это может только создать поле для ошибок. Поэтому сразу инициализируем две пары RegisterPin для включения двух реле в ветке и две пары RegisterPin для их выключения.

2020-07-14 14:05 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +// ----------------------------------------
@VShurdov 
Ну а здесь реализовал основные функции с комментариями.

2020-07-16 20:36 UTC, VShurdov commented on Firmware/Source/Controller/Commutation.h
> +	RegisterPin TurnOn2;
```suggestion
	RegisterPin TurnOn2;
Нет необходимости указывать 2 реле, т.к. соединены между собой и управляются одной цепью.
```

2020-07-16 20:40 UTC, VShurdov commented on Firmware/Source/Controller/Commutation.h
> +	RegisterPin TurnOff2;
Нет необходимости указывать 2 реле, т.к. соединены между собой и управляются одной цепью.

2020-07-16 20:53 UTC, VShurdov commented on Firmware/Source/Controller/Commutation.c
> +void COMM_Examle()
Exam**p**le

2020-07-16 21:11 UTC, VShurdov commented on Firmware/Source/Controller/Commutation.h
> +	RegisterPin TurnOff2;
Оба реле сидят на одной цепи управления.

2020-07-17 12:55 UTC, asytyi commented
Мне не очень нравится вариант работы с RAW масками даже в отладочных целях. Реле целая куча, тем более с бистабильными можно легко ошибиться с заданием маски включения и выключения. Сейчас закоммичу свой вариант.

2020-07-17 14:19 UTC, asytyi commented on Firmware/Source/Controller/Controller.c
> +volatile Int8U RelayByte[11];
Мёртвая переменная так и висит 💀

2020-07-17 14:38 UTC, asytyi commented
Итак, что я сделал в последнем коммите:
1. Всё что касается определений пинов перенёс в CommutationTable, чтобы в Commutation остались только функции
2. Создал массивы с указателями на наши переменные с параметрами пинов, чтобы к ним можно было иметь доступ по индексу, но в то же время определение не дублировалось. Это понадобится для отладочных функций.

Благодаря вышеописанному манёвру в Commutation.c к пину `COMM_SwitchBUSLVPlusToPOW1` можно получить доступ следующим образом: `*COMM_BistableRelayArray[0]`. Ну а, например, включить реле с помощью:

`COMM_SwitchBistableDevice(*COMM_BistableRelayArray[0], true);`

Теперь, чтобы подрыгать реле в отладочном режиме, не надо прыгать с масками. Достаточно завести 4 отладочные команды на подключение и отключение
```
#define ACT_DBG_SIMPLE_RELAY_CONNECT 10
#define ACT_DBG_SIMPLE_RELAY_DISCONNECT 11
#define ACT_DBG_BISTABLE_RELAY_CONNECT 12
#define ACT_DBG_BISTABLE_RELAY_DISCONNECT 13
```
и через один регистр `REG_DBG_RELAY_INDEX` передавать номер реле (или номер бистабильной ветки) в массивах `COMM_SimpleRelayArray` и `COMM_BistableRelayArray`

2020-07-17 15:04 UTC, asytyi requested changes

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Platform/DeviceObjectDictionary.h
> +#define REG_GROUP_RELAY					150	// ������� ��������� ���������������� ������
Со 128го начинаются основные рабочие регистры. Отладочные должны начинаться примерно с 140-150

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +void COMM_ConnectRelayGroup(uint8_t Group)
На данном этапе это лишняя неполноценная функция

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +void COMM_SetRelayFromRAW()
Это надо убрать

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +// ----------------------------------------
Это тоже лишнее

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +	CONTROL_DelayMs(500);
1. Никаких числовых значений за редким исключением не должно быть в коде. Все такие вещи дефайнятся в Global.h
2. Почему задержка такая большая?

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +		SPI_WriteByte(SPI1, ShiftRegistersState[i]);
Для SPI_WriteByte нужна обёртка в LowLevel. Так оно не будет работать, нет управления CS и ОЕ. Посмотри как это реализовано [здесь](https://github.com/lardc/hw-TOMUHPControlBoard/blob/fbd27857006e473e7caba4d4cdd4bf65d02f9aa8/Firmware/Source/Controller/Commutation.c#L44).

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +// ----------------------------------------
```suggestion
void COMM_CleanBistable()
{
	for(uint8_t i = 0; i < REGISTERS_NUM; i++)
	{
		ShiftRegistersState[i] &= BistableBits[i];
		BistableBits[i] = 0;
	}
}
// ----------------------------------------
void COMM_DisconnectBistable()
{
	for(uint8_t i = 0; i < REGISTERS_NUM; i++)
	{
		ShiftRegistersState[i] &= ~BistableBits[i];
		BistableBits[i] = 0;
	}

	COMM_ApplyCommutation();
}
// ----------------------------------------
```
Зачем эта функция модифицирована? Зачем разделять очистку бистабильных бит и применение этой операции, если они всегда вызываются вместе? Чтобы потом так писать?
```
	COMM_CleanBistable();
	COMM_ApplyCommutation();
```
Дублирование кода и поле для ошибок.
И да, не хватает инверсии `~BistableBits[i]`

2020-07-17 15:04 UTC, asytyi commented on Firmware/Source/Controller/Commutation.c
> +	BistableBits[REGISTER_G] = 0xFF;
Такая реализация не годится. Одновременная подача тока 400мА на 24 реле? 10А тока?

2020-07-18 13:37 UTC, VShurdov commented on Firmware/Source/Platform/DeviceProfile.c
> +			SCCI_TIMEOUT_TICKS, 0);
У меня автоформатирование не делает отступ в 81 и 83 сроках. Странно почему

2020-07-20 13:46 UTC, asytyi commented
Внёс исправления в проект. Внимательно изучи каждый мой сегодняшний коммит и проанализируй, почему код был переписан. Если будут вопросы — задавай.
Делаю это только для того, чтобы задача была завершена. В следующий раз такой код не будет принят.

2020-07-20 13:46 UTC, asytyi approved these changes

2020-07-20 19:46 UTC, merged